In [1]:
import tensorflow as tf
tf.__version__

'2.7.0'

In [2]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
scalar.ndim

0

In [4]:
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
vector.ndim

1

In [6]:
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [7]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))



In [8]:
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [9]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))

In [10]:
random_1 == random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

In [11]:
import numpy as np
numpy_A = np.arange(1,25)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [12]:
tf.constant(numpy_A)

<tf.Tensor: shape=(24,), dtype=int64, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])>

In [13]:

rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])

In [14]:
rank_3_tensor = rank_2_tensor[..., tf.newaxis] # in Python "..." means "all dimensions prior to"
rank_2_tensor, rank_3_tensor

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
 array([[[10],
         [ 7]],
 
        [[ 3],
         [ 4]]], dtype=int32)>)

In [15]:
tf.expand_dims(rank_2_tensor,axis=-1)# -1 means expand the final axis


<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [16]:
tf.expand_dims(rank_2_tensor,axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

### Manipulating tensors

In [17]:
tensor = tf.constant([[10,7],[3,4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [18]:
#Similarly other operations will also work

In [19]:
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [20]:
# Create a tensor with 50 random values between 0 and 100
E = tf.constant(np.random.randint(low=0, high=100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([73, 90, 83,  8, 28,  2, 12, 79, 60, 28, 48, 52, 68, 45, 16, 81, 45,
       13, 60, 96, 82, 69, 76, 38, 11, 55,  6, 35, 83, 72, 13, 76, 89, 82,
       14, 69, 47, 37, 94, 95, 99, 54, 99, 87, 50, 66, 56, 82, 23,  7])>

In [28]:
tf.size(E)

<tf.Tensor: shape=(), dtype=int32, numpy=50>

In [24]:
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2>

In [29]:
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [31]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2753>

Variance

In [32]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=55>

In [33]:
import tensorflow_probability as tfp
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=867>

In [36]:
tfp.stats.stddev(E)

InvalidArgumentError: ignored

In [44]:
tf.math.reduce_std((tf.cast(E,dtype=tf.float32)))

<tf.Tensor: shape=(), dtype=float32, numpy=29.460081>

In [47]:
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.56310785, 0.9944345 , 0.8163613 , 0.6350905 , 0.43795872,
       0.3545252 , 0.59824586, 0.22095692, 0.8296001 , 0.3106295 ,
       0.8009968 , 0.5361128 , 0.8759365 , 0.23324311, 0.7403554 ,
       0.51752055, 0.3323748 , 0.12618494, 0.02355361, 0.23644555,
       0.95327425, 0.974067  , 0.01001799, 0.0294795 , 0.3859849 ,
       0.5824058 , 0.6370616 , 0.7482729 , 0.6983659 , 0.6759634 ,
       0.01576662, 0.800459  , 0.16335881, 0.3460269 , 0.6009593 ,
       0.7740443 , 0.04389131, 0.5051724 , 0.9409809 , 0.6079124 ,
       0.72437215, 0.1941756 , 0.5330353 , 0.7521769 , 0.3413583 ,
       0.47095752, 0.39655364, 0.03951538, 0.59440756, 0.05545056],
      dtype=float32)>

In [48]:
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [49]:
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=22>

In [50]:
F[tf.argmin(F)], F[tf.argmax(F)]

(<tf.Tensor: shape=(), dtype=float32, numpy=0.010017991>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.9944345>)

Squeezing a tensor

In [51]:
G = tf.constant (tf.random.uniform(shape=[50]), shape = (1,1,1,1,50))

In [52]:
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.5903019 , 0.9857    , 0.54226923, 0.5697676 , 0.3546399 ,
           0.6395328 , 0.7055768 , 0.0787015 , 0.2259196 , 0.1939224 ,
           0.3955959 , 0.8779886 , 0.73836124, 0.5333986 , 0.8896781 ,
           0.6775156 , 0.45642805, 0.01079595, 0.98829794, 0.7549465 ,
           0.2295661 , 0.83982027, 0.2992773 , 0.18340516, 0.8682096 ,
           0.17061114, 0.4167086 , 0.445248  , 0.8761684 , 0.14038873,
           0.5781419 , 0.27926564, 0.97502804, 0.465778  , 0.29540396,
           0.7774216 , 0.688624  , 0.48224962, 0.24800193, 0.3897295 ,
           0.9675571 , 0.40869427, 0.9333439 , 0.7186098 , 0.62201405,
           0.44003582, 0.84467876, 0.4094305 , 0.0209434 , 0.8309568 ]]]]],
      dtype=float32)>

In [53]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [54]:
G_squeezed = tf.squeeze(G)
G_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.5903019 , 0.9857    , 0.54226923, 0.5697676 , 0.3546399 ,
       0.6395328 , 0.7055768 , 0.0787015 , 0.2259196 , 0.1939224 ,
       0.3955959 , 0.8779886 , 0.73836124, 0.5333986 , 0.8896781 ,
       0.6775156 , 0.45642805, 0.01079595, 0.98829794, 0.7549465 ,
       0.2295661 , 0.83982027, 0.2992773 , 0.18340516, 0.8682096 ,
       0.17061114, 0.4167086 , 0.445248  , 0.8761684 , 0.14038873,
       0.5781419 , 0.27926564, 0.97502804, 0.465778  , 0.29540396,
       0.7774216 , 0.688624  , 0.48224962, 0.24800193, 0.3897295 ,
       0.9675571 , 0.40869427, 0.9333439 , 0.7186098 , 0.62201405,
       0.44003582, 0.84467876, 0.4094305 , 0.0209434 , 0.8309568 ],
      dtype=float32)>

In [55]:
G_squeezed.shape

TensorShape([50])

One-hot encoding tensors

In [56]:
some_list = [0,1,2,3]

In [62]:
tf.one_hot(some_list,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>



Tensors and Numpy




In [63]:
j = tf.constant(np.array([3.,5.,7.]))
j

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([3., 5., 7.])>

In [64]:
np.array(j)

array([3., 5., 7.])